openapi: 3.0.0
info:
  version: 1.0.0
  title: Project Milestone 2
  description: Task manager webs app
servers:
  - url: https://week11-rpb.up.railway.app
    description: 'production server'
  - url: http://localhost:4000
    description: 'Development server'
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'
paths:
  /v1/auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: rpb
              password: manager123
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /v1/auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
            example:
              username: aaaaa
              password: aaaa1111
              role: employee
      responses:
        '200':
          description: Successful response
        '400':
          description: Wrong input requirement
  /v1/users:
    get:
      summary: get all user
      parameters: []
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error
  /v1/users/{userId}:
    get:
      summary: get one user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    delete:
      summary: delete one user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    patch:
      summary: update user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
            example:
              username: notnull
              password: alphaNumeric1
              role: employee
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /v1/tasks:
    post:
      summary: create new task
      security:
        - bearer_auth: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
            example:
              task: make weekly report
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error
  /v1/tasks/{taskId}:
    get:
      summary: get one task
      security:
        - bearer_auth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
    patch:
      summary: update task status
      security:
        - bearer_auth: []      
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
            example:
              status: In progress
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
    delete:
      summary: soft delete task
      security:
        - bearer_auth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
  /:
    get:
      summary: Rest API home
      responses:
        '200':
          description: Successful response
